hugoblox:
  schema: "2.0"
  identity:
    name: Dhruv Ajmera
    type: person
    tagline: Student/Researcher | UT Austin
    description: "Dhruv Ajmera is an undergraduate student at UT Austin. "
  theme:
    mode: system
    pack: coffee
    colors:
      primary: ""
      secondary: ""
      neutral: ""
  typography:
    font: sans
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: true
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: Â© {year} {name}
  content:
    math:
      enable: true
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true
